fabric:
  bastion:
    hostname: bastion-1.fabric-testbed.net
    port: 22
    private:
      ipv4: 192.168.11.226
      ipv6: 2600:2701:5000:a902::c
  credmgr:
    hostname: cm.fabric-testbed.net
  orchestrator:
    hostname: orchestrator.fabric-testbed.net